### ISSUE TITLE
server.py: AttributeError: module 'tornado.platform' has no attribute 'asyncio' 

### ISSUE THREAD

**Issue by AutreTechLab** [AutreTechLab/ATL_Blockly_Suite#1]
autretechlab@SSH-UDT-V-02:~/Documents/cozmo-blockly/server$ **python3 server.py** 

[Server] Starting server...
Traceback (most recent call last):
  File "server.py", line 234, in <module>
    main()
  File "server.py", line 231, in main
    CozmoBlockly.start(args)
  File "server.py", line 199, in start
    tornado.platform.asyncio.AsyncIOMainLoop().install()
AttributeError: module 'tornado.platform' has no attribute 'asyncio'
autretechlab@SSH-UDT-V-02:~/Documents/cozmo-blockly/server$ events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:9091
    at Server.setupListenHandle [as _listen2] (net.js:1301:14)
    at listenInCluster (net.js:1349:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1488:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1328:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9091
}

**Comment by AutreTechLab** [comment]
fixed by adding "from tornado.platform.asyncio import AsyncIOMainLoop" to the server.py
